[build]
  # Đường dẫn đến thư mục build của client
  base = "client"
  publish = "client/build"
  command = "npm run build"

[[redirects]]
  # Chuyển hướng tất cả request đến index.html cho ứng dụng React (SPA)
  from = "/*"
  to = "/index.html"
  status = 200
